### ISSUE TITLE
React 15.2 Unknown props

### ISSUE THREAD

**Issue by phil3903** [dantrain/react-stonecutter#10]
With React 15.2+ I'm seeing the unknown props warning in react-stonecutter: 

Warning: Unknown props `columnWidth`, `gutterWidth`, `gutterHeight`, `minPadding`, `columns`, `angleUnit`, `layout`, `enter`, `entered`, `exit` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

and 

Warning: Unknown prop `itemRect` on <div> tag. Remove this prop from the element.

Not sure what FB changed but lots of libs are tossing these warnings now. Stonecutter still works, but just wanted to give you a heads up.

**Comment by dantrain** [comment]
Hi, thanks a lot for the heads up. I've created a new release that should fix this.
