### ISSUE TITLE
Drag & Drop reorder

### ISSUE THREAD

**Issue by mishoboss** [dantrain/react-stonecutter#19]
Any plans to implement Drag & Drop reorder of panels? That would be a killing feature!

**Comment by mishoboss** [comment]
Over a month without answer. Is this project still supported?

**Comment by dantrain** [comment]
Yes all current features are supported. No plans for drag and drop as yet.
If you plan on adding this maybe have a look at integrating https://github.com/gaearon/react-dnd?
