### ISSUE TITLE
Images are overlapped. 

### ISSUE THREAD

**Issue by manimuthukumar6** [dantrain/react-stonecutter#2]
Hi ,

I don't know the heights of my items ahead of time and try to use the measureItems higher-order component to measure them in the browser before layout using the following snippet.

import { SpringGrid, measureItems } from 'react-stonecutter';

const Grid = measureItems(SpringGrid);
<Grid
  component="ul"
  columns={3}
  columnWidth={350}
  gutterWidth={3}
  gutterHeight={3}
  layout={layout.pinterest}

>   <li key="A">IMG A</li>
>   <li key="B">IMG B</li>
>   <li key="C">IMG C</li>
>   <li key="D">IMG D</li>
> </Grid>

But I am getting all images are overlapped with the single image. Any idea about this issue. I want to implement "Pinterest grid layout".

![image](https://cloud.githubusercontent.com/assets/417217/14808850/593affc8-0ba6-11e6-9560-e48f9660a8cb.png)

**Comment by dantrain** [comment]
Hi there,

This is probably because `measureItems` measures the element heights immediately when the images have not yet loaded. The solution might be to wait for the images to fully load before measuring them and adding them to the grid.

`measureItems` could be modified to use a library such as [imagesLoaded](https://github.com/desandro/imagesloaded) to achieve this. I might take a look at this in future.

The easiest is not to use `measureItems` at all, maybe there's a way for you to know the image dimensions ahead of time and set the `itemHeight` props explicitly?

**Comment by manimuthukumar6** [comment]
Hi ,

Currently, I am not sure about to the exact image height. It's dynamically loaded. I want to be implement like as Pinterest using react and jsx components.

Do you have any idea to combine imagesLoaded and react-stonecutter component using Vanilla JavaScript ?

I mean using " imagesLoaded( elem, options, callback ) " , is it possible to call the react-stonecutter component using callback ?

Thanks,
Mani

**Comment by dantrain** [comment]
Hi Mani,

I've updated `measureItems` so now you can pass an option to measure the images, something like this:

```js
const Grid = measureItems(SpringGrid, { measureImages: true })
```

Could you give it a try?

**Comment by shaan-toko** [comment]
Hey @dantrain, I tried using the `measureImages` option in `measureItems` but still it is not able to calculate the proper height of the item. My item contains image and a title, both with dynamic heights. Any solutions?

Heres the image:
![Overlapping items](https://cloud.githubusercontent.com/assets/22494357/22507999/0dbcfb42-e8ae-11e6-809e-ad43452ef997.png)

**Comment by dantrain** [comment]
Hi there, that code all looks ok to me. I'm working on a test case to see if I can reproduce this problem. Sorry for the delay.

**Comment by dantrain** [comment]
Could you take a look at this example project and see how it compares?

https://github.com/dantrain/stonecutter-images-example

**Comment by horaciosystem** [comment]
Hi @dantrain I take a look in your example but the problem continues.
I think you should change your example to load data async, from some placeholder image web site, then I'm pretty sure you will see the overlapping happening.
