### ISSUE TITLE
Dynamic height calculation not working properly when images are getting loaded

### ISSUE THREAD

**Issue by mkliu** [dantrain/react-stonecutter#23]
If it's a new image getting loaded, the calculation is wrong and panels are overlaying cross each other, any suggestions?

**Comment by mkliu** [comment]
Any way I could force to recalculate height?

**Comment by dantrain** [comment]
Hey, what's the use case exactly? `{ measureImages: true }` is meant to wait for images to load before doing the measurement. Are you adding a new image to an existing grid item after it's already been measured and laid out?

**Comment by mkliu** [comment]
aha! I missed that config! Sorry I didn't see it. I even ended up implementing the same thing myself.
