### ISSUE TITLE
gutterWidth is necessary for makeResponsive column calculation

### ISSUE THREAD

**Issue by KaiSchniggendiller** [dantrain/react-stonecutter#30]
gutterWidth={0} is necessary for makeResponsive column calculation. u should add the default gutterWidth value (0) to the calculation otherwise it will always display 4 columns (defaultColumns) 

![gutterwidth](https://user-images.githubusercontent.com/8722534/28567166-bde67a96-7131-11e7-954d-6765741e8943.jpg)

**Comment by dantrain** [comment]
Good spot thanks I'll get this fixed.

**Comment by dantrain** [comment]
Should be fixed in v0.3.6.
