### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by AlexeyPruss** [dantrain/react-stonecutter#33]
Do you have plans on supporting react 16 in your library?

**Comment by dantrain** [comment]
Hello, yes I plan to add this as soon as possible however I won't be free to work on this for a couple of weeks so please be patient! Thank you.

**Comment by dantrain** [comment]
I did not have to make any changes for React 16, I am just waiting for dev dependencies to update before publishing a new version. You should be able to ignore the peer dependency warnings until then.
