### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by mquandalle** [dantrain/react-stonecutter#44]
Hi,

I'm using react-stonecutter on a server-side rendered page. You can see the example here: https://smartariffa.it/.

The server-side rendering is working, you can see that the cards content is present in the html source, search for “Senza limiti” for instance. However when the page loads the cards aren't displayed, until the Stonecutter layout calculation is done (I'm using `measureItems` with a custom layout and a `SpringGrid`) — which takes about 1 sec in the above example.

Do you have any idea why stonecutter “re-hydrating” isn't working as for other React server-side rendered components, and do you have any pointer about how to fix this issue?

**Comment by erikleon** [comment]
Any resolution on this?
